[project]
name = "qry-proyect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandasai-openai>=0.1.6",
    "qry-doc[all]>=0.1.0",
]
